---
title: "Circular regression Test"
author: "kotsubo takuto"
#date: "2018年2月8日"
output: 
    html_document:
      md_extensions: -ascii_identifiers
      toc: true
      toc_depth: 3
---

```{r option, echo=FALSE, cache=FALSE, warning=FALSE}
library(knitr)
## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
               #cache = TRUE, # 現状大きな計算はしていないので
	             prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r,echo=FALSE}
library(dplyr)
library(tidyverse)
library(pipeR)
library(lubridate)
library(circular)
library(readr)
library(ggplot2)
library(ggthemes)
library(vars)
source('~/Desktop/circular_reg/script/function.R')
```

# データ準備

## データ読み込み

```{r, eval=FALSE,include=FALSE}
# 練馬区風向データ 気象庁データより作成
col_names <- c("data","wind","info1","info2")
data <- read_csv("csv/nerima_wind.csv",col_names = col_names,skip=6,locale=locale(encoding='Shift_JIS'))
glimpse(data)
```

```{r}
data(wind) # in this dataset we report the wind direction recorded every day from January 29, 2001 to March 31, 2001 from 3.00am to 4.00am included.
wind %>% 
  data.frame(p = seq(1,310,1), theta=.) -> wind_data 
glimpse(wind_data)  
```

## データ整形

風向データが16方位で与えられているので, 角度データに変更する. その際, 東を0度, 北を90度とする.

```{r, eval=FALSE,include=FALSE}
# 風向データの値を16方位から角度データに変換する.
data %>% 
  mutate(theta = ifelse(wind == "東",0,
                 ifelse(wind == "東北東",22.5,
                 ifelse(wind == "北東",45,
                 ifelse(wind == "北北東",67.5,
                 ifelse(wind == "北",90,
                 ifelse(wind == "北北西",112.5,
                 ifelse(wind == "北西",135,
                 ifelse(wind == "西北西",157.5,
                 ifelse(wind == "西",180,
                 ifelse(wind == "西南西",202.5,
                 ifelse(wind == "南西",225,
                 ifelse(wind == "南南西",247.5,
                 ifelse(wind == "南",270,
                 ifelse(wind == "南南東",292.5,
                 ifelse(wind == "南東", 315,337.5)))))))))))))))) -> data
```

## Time Series Plot

```{r}
ggplot(data = wind_data, mapping = aes(x=p,y=theta)) +
  geom_line() + 
  theme_economist() +
  labs(title = "time series circular plot")
```

```{r}
wind_data %>% 
  mutate(cos = cos(theta), sin=sin(theta)) %>% 
  tidyr::gather(key = "variable",value  = value, cos,sin) %>% 
  ggplot(aes(x=p,y=value,colour=variable)) +
   geom_line() + 
   theme_economist() +
   labs(title = "time series circular plot")
```

## circular package

数式が Sarma, Y. and Jammalamadaka, S.(1993) に準じている.

```{r}
pred_saram <- lm.circular(y = wind_data$theta[3:310], x = wind_data$theta[1:308], type = "c-c", order=2)
pred_saram <- lm.circular(y = wind_data$theta[3:7], x = wind_data$theta[1:5], type = "c-c", order=2)

# Obtain a crude plot of the data and fitted regression line.
pred_saram$fitted[pred_saram$fitted>pi] <- pred_saram$fitted[pred_saram$fitted>pi] - 2*pi
plot.new()
points.default(x[order(x)], pred_saram$fitted[order(x)], type='l')
```

`lm.circular`関数はある説明変数のベクトル, 応答変数のベクトルで回帰する. circular.regでは逐次更新していくのでは？？

## Vars

```{r}
wind_data %>% 
  mutate(cos = cos(theta),sin = sin(theta)) %>% 
  select(cos,sin) %>% 
  VAR(p=2,type="const") -> wind_data_pred
```

```{r}
# Generate parameter
# もっと綺麗に書ける
Bcoef(wind_data_pred) %>% 
  as.data.frame() -> alpha
alpha <- alpha$const %>% as.matrix()
beta <- Acoef(wind_data_pred) %>% as.array()
Eps <- summary(wind_data_pred)$covres
Bcoef(wind_data_pred) -> a
```

```{r}
pred <- CircularRegPred(wind_data$theta,2,alpha,beta,Eps)
```

```{r}
pred %>% 
  tidyr::gather(key = "variable",value  = value, cos,sin) %>% 
  ggplot(aes(x=p,y=value,colour=variable)) +
   geom_line() + 
   theme_economist() +
   labs(title = "time series circular plot")
```


